HRX_ENV_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

. "${HRX_ENV_DIR}/versions.sh"

: "${HRX_WORK_DIR:=${RUNNER_TEMP:-/tmp}}"
: "${HRX_SRC_DIR:=${HRX_WORK_DIR}/hrx-src}"
: "${HRX_ROCM_ROOT:=${ROCM_PATH:-${HRX_WORK_DIR}/hrx-rocm-root}}"
: "${HRX_DOWNLOAD_CACHE_DIR:=${HRX_WORK_DIR}/hrx-rocm-downloads}"
: "${HRX_BUILD_DIR:=${HRX_WORK_DIR}/hrx-build}"
: "${HRX_INSTALL_PREFIX:=${HRX_WORK_DIR}/hrx-install}"
: "${HRX_REPOSITORY:=${HRX_VERSION_REPOSITORY}}"
: "${HRX_FETCH_REF:=${HRX_VERSION_FETCH_REF}}"
: "${HRX_CHECKOUT_REF:=${HRX_REF:-${HRX_VERSION_REF}}}"
: "${LLAMA_SRC_DIR:=${HRX_WORK_DIR}/llama-src}"
: "${LLAMA_BUILD_DIR:=${LLAMA_SRC_DIR}/build-hrx}"
: "${LLAMA_REPOSITORY:=${LLAMA_VERSION_REPOSITORY}}"
: "${LLAMA_FETCH_REF:=${LLAMA_VERSION_FETCH_REF}}"
: "${LLAMA_CHECKOUT_REF:=${LLAMA_REF:-${LLAMA_VERSION_REF}}}"
: "${HRX_ARTIFACT_SET:=core-with-upstream-hip}"
: "${HRX_EXTRA_ROCM_ARTIFACTS:=rocwmma_dev_gfx110X-all}"
: "${CMAKE_BUILD_TYPE:=Release}"
: "${CMAKE_GENERATOR:=Ninja}"

export HRX_WORK_DIR
export HRX_SRC_DIR HRX_ROCM_ROOT HRX_DOWNLOAD_CACHE_DIR
export HRX_BUILD_DIR HRX_INSTALL_PREFIX
export HRX_REPOSITORY HRX_FETCH_REF HRX_CHECKOUT_REF
export LLAMA_SRC_DIR LLAMA_BUILD_DIR LLAMA_REPOSITORY LLAMA_FETCH_REF LLAMA_CHECKOUT_REF
export HRX_RELEASE_TYPE HRX_RUN_ID HRX_ARTIFACT_SET HRX_EXTRA_ROCM_ARTIFACTS
export CMAKE_BUILD_TYPE CMAKE_GENERATOR
